services:
  - type: web
    name: dropheic-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: FRONTEND_URL
        value: https://dropheic-woad.vercel.app
    disk:
      name: uploads-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
