services:
  - type: web
    name: dropheic-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://your-frontend-url.onrender.com # Update this
    disk:
      name: uploads-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
